---
- name: nDVP | Add iSCSI package
  become: true
  yum: name={{ item }} state=latest
  with_items:
    - lsscsi
    - iscsi-initiator-utils
    - sg3_utils
    - device-mapper-multipath
  when: ansible_os_family == 'RedHat'

- name: nDVP | Enable iSCSI
  become: true
  shell: mpathconf --enable --with_multipathd y

- name: nDVP | Enable iscsid and multipathd
  become: true
  systemd: name={{ item }} enabled=yes state=started
  with_items:
    - iscsid
    - multipathd

- name: nDVP | Create config folder
  become: true
  file:
    path: /etc/netappdvp
    state: directory

- name: nDVP | Copy configuration file
  become: true
  copy:
    src: configSAN.json
    dest: /etc/netappdvp/configSAN.json

- name: nDVP | Discover
  become: true
  shell: iscsiadm -m discoverydb -t st -p "{{ nDVP_IP }}" --discover

- name: nDVP | Login
  become: true
  shell: iscsiadm -m node -p "{{ nDVP_IP }}" --login 

- name: nDVP | Enable and start iscsi
  become: true
  systemd: name={{ item }} enabled=yes state=started
  with_items:
    - iscsi

- name: nDVP | Install plugin for SAN
  become: true
  shell: docker plugin install --grant-all-permissions --alias netappsan netapp/ndvp-plugin:17.07 config=configSAN.json
