---

# Remove UCP
- hosts: all
  roles:
  - role: remove-ucp

# Leave swarm
- hosts: all
  roles:
  - role: remove-swarm

# Remove Docker daemon
- hosts: all
  roles:
  - role: remove-docker
  tags:
  - daemon
