---

# Pre-install | Create user
- hosts: all
  roles:
  - role: create-user
  tags:
  - user

# Pre-install | Setup RedHat subscription
- hosts: all
  roles:
  - role: rhel-subscription
  tags:
  - subscription

# Pre-install | NTP
- hosts: all
  roles:
  - role: setup-ntp
  tags:
  - ntp

# Pre-install | NFS client
- hosts: all
  roles:
  - role: setup-nfs
  tags:
  - nfs

# Pre-install | Disable firewalld
- hosts: all
  roles:
  - role: remove-firewalld
  tags:
  - firewalld
